apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-runner
  namespace: gitea
  labels:
    app: gitea-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-runner
  template:
    metadata:
      labels:
        app: gitea-runner
    spec:
      containers:
        - name: runner
          image: gitea/act_runner:latest
          env:
            - name: GITEA_INSTANCE_URL
              value: "http://gitea-http.gitea.svc.cluster.local:3000" # For externals IPs, you should add your external URL. 
            - name: GITEA_RUNNER_REGISTRATION_TOKEN
              value: "GD4yEOdZOXOYHJRRLAklv89NHu3uxDl3XiaWxuch" # You have to get it in your gitea. 
            - name: GITEA_RUNNER_NAME. # This name is showed in Runner section, choose a descriptive name.
              value: "k8s-runner"
            - name: GITEA_RUNNER_LABELS # This labels are important to your workflow pipelines, chose an ubiquous labels.
              value: "kubernetes"
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
